name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'media/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'media/**'
  workflow_dispatch:

jobs:
  fmt-tests-clippy:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install for egui
        run: sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libgtk-3-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Check default features
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings
